
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EJ
 */
public class SubjectLoading extends javax.swing.JFrame {

    /**
     * Creates new form SubjectLoading
     */
    
    CollegeQuery colQ = new CollegeQuery();
    ArrayList<College> colList = colQ.collegeList();  // this contains the list of college records
    InstructorQuery insQ = new InstructorQuery();
    ArrayList<Instructor> instructList = insQ.instructorList(null); // this contains the list of instructor records
    String Emp_ID;
    
    public SubjectLoading() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.BLACK);
        jTable1.setSelectionBackground(Color.lightGray);
        
        JTableHeader th = jTable1.getTableHeader();
        th.setForeground(Color.BLACK);
        th.setFont(new Font("Arial", Font.BOLD, 14));
        
        fillComboCollege();
        fillComboInstructor();
        
    }
    
    public void fillComboCollege()
    {
        jComboBox2.addItem("All");
        for(int i=0;i < colList.size(); i++)
        {
            jComboBox2.addItem(colList.get(i).getCollege_name());
        }
    }
    
    public void fillComboInstructor()
    {
        jComboBoxInstructor.addItem("Please select");
        System.out.println(instructList.size());
        for(int i=0; i< instructList.size(); i++)
        {
            jComboBoxInstructor.addItem(instructList.get(i).getName());
        }
        
    }
    
    public void populateTable(String id)
    {
        CourseLoadQuery clq = new CourseLoadQuery();
        ArrayList<Course> cLoadList = clq.courseLoadList(id);
        String[] colNames = {"Course ID", "Course Name", "College ID", "Instructor Name"};
        Object[][] rows = new Object[cLoadList.size()][4];
        for(int i=0; i < cLoadList.size(); i++)
        {
            rows[i][0] = cLoadList.get(i).getCourse_id();
            rows[i][1] = cLoadList.get(i).getCourse_name();
            rows[i][2] = cLoadList.get(i).getCollege_id();
            rows[i][3] = cLoadList.get(i).getEmployee_id();
        }
        MyModel mmd = new MyModel(rows, colNames);
        jTable1.setModel(mmd);
        jTable1.setRowHeight(50);        
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(120);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelExit = new javax.swing.JLabel();
        labelMinimize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelLoginForm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxInstructor = new javax.swing.JComboBox<>();
        jButtonAssign = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCourseName = new javax.swing.JTextField();
        jTextFieldCourseID = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButtonUnassign = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 173, 181));

        labelExit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelExit.setText("x");
        labelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });

        labelMinimize.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelMinimize.setText("-");
        labelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizeMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(57, 62, 70));
        jPanel2.setLayout(null);

        labelLoginForm.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labelLoginForm.setForeground(new java.awt.Color(245, 245, 245));
        labelLoginForm.setText("Loading of Subjects");
        jPanel2.add(labelLoginForm);
        labelLoginForm.setBounds(220, 10, 230, 26);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("College:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(100, 60, 70, 26);

        jComboBoxInstructor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jComboBoxInstructor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInstructorActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxInstructor);
        jComboBoxInstructor.setBounds(360, 390, 150, 27);

        jButtonAssign.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAssign.setText("ASSIGN");
        jButtonAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssignActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAssign);
        jButtonAssign.setBounds(530, 390, 100, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(16, 106, 620, 240);

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBack);
        jButtonBack.setBounds(10, 10, 55, 28);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Instructor Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(360, 370, 120, 18);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course ID");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 370, 80, 18);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Course Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(150, 370, 100, 18);

        jTextFieldCourseName.setEditable(false);
        jTextFieldCourseName.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldCourseName.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTextFieldCourseName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextFieldCourseName);
        jTextFieldCourseName.setBounds(150, 390, 190, 28);

        jTextFieldCourseID.setEditable(false);
        jTextFieldCourseID.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldCourseID.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTextFieldCourseID.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextFieldCourseID);
        jTextFieldCourseID.setBounds(20, 390, 110, 30);

        jComboBox2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(170, 60, 320, 27);

        jButtonUnassign.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonUnassign.setText("UNASSIGN");
        jButtonUnassign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnassignActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonUnassign);
        jButtonUnassign.setBounds(530, 430, 100, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelExit)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExit)
                    .addComponent(labelMinimize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelExitMouseClicked

    private void labelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_labelMinimizeMouseClicked

    private void jComboBoxInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInstructorActionPerformed
        int index = jComboBoxInstructor.getSelectedIndex();
        if(index!=0)
        {
            index--;
            Emp_ID = instructList.get(index).getEmpid();
            System.out.println(Emp_ID);
        }
    }//GEN-LAST:event_jComboBoxInstructorActionPerformed

    private void jButtonAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAssignActionPerformed
        CourseLoadQuery clq = new CourseLoadQuery();
        if(jTextFieldCourseID.equals("") && jComboBoxInstructor.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this, "Please select course or instructor");
        }  
        else
        {  clq.updateCourseInstructor(Emp_ID, jTextFieldCourseID.getText());
           populateTable(null);
           jTextFieldCourseID.setText("");
           jTextFieldCourseName.setText("");
           jComboBoxInstructor.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jButtonAssignActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int rowIndex = jTable1.getSelectedRow();
        jTextFieldCourseID.setText(jTable1.getValueAt(rowIndex, 0).toString());
        jTextFieldCourseName.setText(jTable1.getValueAt(rowIndex, 1).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        mainMenu mm = new mainMenu();
        mm.setVisible(true);
        mm.pack();
        mm.setLocationRelativeTo(null);
        mm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        int index = jComboBox2.getSelectedIndex();
        // index =1
        if(index==0)
        {
            populateTable(null);
        }

        else
        {
            index--; // index = 0
            colList.get(index); // colList.get(0)..getCollegeID()
            System.out.println(colList.get(index).getCollege_id()+""); // CLA
            String ID = colList.get(index).getCollege_id();
            // ID = "CLA"
            //populateTable("CLA")
            populateTable(ID);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButtonUnassignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnassignActionPerformed
        CourseLoadQuery clq = new CourseLoadQuery();
        if(jTextFieldCourseID.equals("") && jComboBoxInstructor.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this, "Please select course or instructor");
        }  
        else
        {  clq.deleteCourseInstructor(null, jTextFieldCourseID.getText());
           populateTable(null);
           jTextFieldCourseID.setText("");
           jTextFieldCourseName.setText("");
           jComboBoxInstructor.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jButtonUnassignActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectLoading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectLoading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectLoading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectLoading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectLoading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAssign;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonUnassign;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxInstructor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCourseID;
    private javax.swing.JTextField jTextFieldCourseName;
    private javax.swing.JLabel labelExit;
    private javax.swing.JLabel labelLoginForm;
    private javax.swing.JLabel labelMinimize;
    // End of variables declaration//GEN-END:variables
}
